CUSTOMERS_file = "data/customers.csv"
BOOKING_file = "data/bookings.csv"
SERVICES_file = "data/services.csv"
MAINTENANCE_file = "data/maintenance.csv"
PAYMENTS_file = "data/payments.csv"
CREDENTIALS_file = "data/credentials.csv"
REQUESTED_BOOKING_file = "data/requested_booking.csv"
REQUESTED_EXTENSION_file = "data/request_extension.csv"
