CUSTOMERS_file = "data/customers.csv"
BOOKING_file = "data/bookings.csv"
SERVICES_file = "data/services.csv"
MAINTENANCE_file = "data/maintenance.csv"
PAYMENTS_file = "data/payments.csv"
CREDENTIALS_file = "data/credentials.csv"